#!/usr/bin/env python3
import random
import math


def generate_graph(edge_count=250, max_weight=10000):
    min_nodes = math.ceil((1 + math.sqrt(1 + 8 * edge_count)) / 2)
    max_nodes = edge_count + 1
    node_count = random.randint(min_nodes, max_nodes)
    terminal = random.randint(3, node_count)
    graph = set()

    nodes = list(range(3, node_count))
    random.shuffle(nodes)
    in_graph = [nodes[0]]

    source1 = nodes.pop()
    source2 = nodes.pop()
    m_s1 = nodes.pop()
    in_graph.append(m_s1)

    # Generate paths to terminal
    path1 = random.sample(nodes, random.randint(1, int(len(nodes) / 2))) + [terminal]
    path2 = (
        [source2]
        + random.sample(nodes, random.randint(1, int(len(nodes) / 2)))
        + [terminal]
    )

    # One heavy "entrypoint" and otherwise small paths makes linear search from top to bottom slow
    graph.add((source1, m_s1, 10000))
    for i in range(len(path1) - 1):
        graph.add((path1[i], path1[i + 1], 1))

    for i in range(len(path2) - 1):
        graph.add((path2[i], path2[i + 1], 1))

    # Add edges randomly
    while len(graph) < edge_count:
        u = random.choice(in_graph)
        v = random.randint(3, node_count)

        if v not in (source1, source2) and u != v:
            graph.add((u, v, random.randint(1, max_weight)))

    with open("linear_top.in", "w") as f:
        f.write(f"{edge_count} {source1} {source2} {m_s1} {terminal}\n")
        for edge in graph:
            f.write(f"{edge[0]} {edge[1]} {edge[2]}\n")


generate_graph()
