#!/usr/bin/env python3
import random
import math


def generate_graph(edge_count=1000, max_weight=10000):
    min_nodes = math.ceil((1 + math.sqrt(1 + 8 * edge_count)) / 2)
    max_nodes = edge_count + 1
    node_count = random.randint(min_nodes, max_nodes)
    graph = set()

    nodes = list(range(0, node_count))
    random.shuffle(nodes)
    in_graph = []

    source1 = nodes.pop()
    source2 = nodes.pop()
    m_s1 = nodes.pop()
    terminal = nodes.pop()
    in_graph.append(m_s1)

    # Generate paths to terminal
    path1 = (
        [source1]
        + [m_s1]
        + random.sample(nodes, random.randint(0, int(len(nodes) / 2)))
        + [terminal]
    )
    path2 = (
        [source2]
        + random.sample(nodes, random.randint(0, int(len(nodes) / 2)))
        + [terminal]
    )

    # One heavy path and one light path makes linear search from bottom to top slow
    for i in range(len(path1) - 1):
        graph.add((path1[i], path1[i + 1], max_weight))
        if i != 0:
            in_graph.append(path1[i])

    for i in range(len(path2) - 1):
        graph.add((path2[i], path2[i + 1], 1))
        if i != 0:
            in_graph.append(path2[i])

    # Add edges randomly
    while len(graph) < edge_count:
        u = random.choice(in_graph)
        v = random.randint(0, node_count)

        if v not in (source1, source2) and u != v and v != terminal:
            in_graph.append(v)
            graph.add((u, v, random.randint(1, max_weight)))

    with open("linear_bottom.in", "w") as f:
        f.write(f"{edge_count} {node_count} {source1} {source2} {m_s1} {terminal}\n")
        for edge in graph:
            f.write(f"{edge[0]} {edge[1]} {edge[2]}\n")


generate_graph()
