#!/usr/bin/env python3
import random
import math


def generate_graph(edge_count=1000, max_weight=10000):
    min_nodes = math.ceil((1 + math.sqrt(1 + 8 * edge_count)) / 2)
    max_nodes = edge_count + 1
    node_count = random.randint(min_nodes, max_nodes)
    graph = set()

    nodes = list(range(0, node_count - 1))
    random.shuffle(nodes)
    in_graph = []

    source = nodes.pop()
    terminal = nodes.pop()

    # Generate paths to terminal
    path_count = random.randint(1, min_nodes)
    paths = []
    for _ in range(path_count):
        paths.append(
            [source]
            + random.sample(nodes, random.randint(0, path_count - 1))
            + [terminal]
        )

    # One heavy path and one light path makes linear search from bottom to top slow
    m_s_path_idx = random.randint(0, path_count)
    m_s_idx = random.randint(0, len(paths[m_s_path_idx]) - 1)
    m_s = paths[m_s_path_idx][m_s_idx]
    m_t = paths[m_s_path_idx][m_s_idx + 1]

    for i in range(len(paths)):
        for j in range(len(paths[i]) - 1):
            if i == m_s_path_idx:
                graph.add((paths[i][j], paths[i][j + 1], max_weight))
            else:
                graph.add((paths[i][j], paths[i][j + 1], 1))
            if paths[i][j] not in in_graph:
                in_graph.append(paths[i][j])

    # Add edges randomly
    while len(graph) < edge_count:
        u = random.choice(in_graph)
        v = random.randint(0, node_count - 1)

        if u != v:
            graph.add((u, v, random.randint(1, max_weight)))
            if v != terminal:
                in_graph.append(v)

    with open("linear_bottom.in", "w") as f:
        f.write(f"{edge_count} {node_count} {source} {terminal} {m_s} {m_t}\n")
        for edge in graph:
            f.write(f"{edge[0]} {edge[1]} {edge[2]}\n")


generate_graph()
